# Illustrate the relations between the indices of the computed scaled $P_{lm}$ 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
index = lambda l, m: l*(l+1)//2 + m

### Create indices up to a given $l_{max}$

In [3]:
# maximum degree
lmax = 6

In [4]:
Plm_matrix = np.zeros((lmax+1,lmax+1))

In [5]:
for l in range(lmax+1):
    for m in range(l+1):
        Plm_matrix[l][m] = index(l, m)

In [6]:
Plm_vector = np.zeros(index(lmax, lmax) + 1)

In [7]:
for l in range(lmax+1):
    for m in range(l+1):
        Plm_vector[index(l, m)] = index(l, m)

In [8]:
print(Plm_matrix)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  2.  0.  0.  0.  0.  0.]
 [ 3.  4.  5.  0.  0.  0.  0.]
 [ 6.  7.  8.  9.  0.  0.  0.]
 [10. 11. 12. 13. 14.  0.  0.]
 [15. 16. 17. 18. 19. 20.  0.]
 [21. 22. 23. 24. 25. 26. 27.]]


In [9]:
print(Plm_vector)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.]


### Relations between sectoral terms $l = m$

In [10]:
for l in range(2, lmax+1):
    print(index(l, l))

5
9
14
20
27


In [11]:
# index of the term defined by P11
index_l_1_l_1 = 2

# index of the term defined by P22
index_ll = 5
    
for l in range(2, lmax+1):
    
    print(index_l_1_l_1, index_ll)

    # update index_l_1_l_1
    index_l_1_l_1 += l + 1
    
    # update index_ll
    index_ll += l + 2

2 5
5 9
9 14
14 20
20 27


### Relations between terms with contant order $m$ and increasing degree $l$

In [24]:
seed_l_1_m = 0
seed_lm = 1
for m in range(lmax):
    index_l_1_m = seed_l_1_m
    index_lm = seed_lm
    print(index_l_1_m, index_lm)
    index_l_2_m = index_l_1_m
    index_l_1_m = index_lm
    index_lm += m + 2
    for l in range(m+2, lmax+1):
        print(index_l_2_m, index_l_1_m, index_lm)
        index_l_2_m = index_l_1_m
        index_l_1_m = index_lm
        index_lm += l + 1
    seed_l_1_m += m + 2
    seed_lm += m + 3
    print('\n')

0 1
0 1 3
1 3 6
3 6 10
6 10 15
10 15 21


2 4
2 4 7
4 7 11
7 11 16
11 16 22


5 8
5 8 12
8 12 17
12 17 23


9 13
9 13 18
13 18 24


14 19
14 19 25


20 26




In [27]:
seed_ll = 2
for m in range(1, lmax+1):
    index = seed_ll
    print(index)
    index += m + 1
    for l in range(m+1, lmax+1):
        print(index)
        index += l + 1
    seed_ll += m + 2
    print('\n')

2
4
7
11
16
22


5
8
12
17
23


9
13
18
24


14
19
25


20
26


27


